name = "UniversalMaterialModel"
uuid = "451d549b-da3a-4afd-9dba-1924b1a1c089"
version = "0.1.0"
authors = ["marinlauber <marinlauber@gmail.com>"]

[deps]
Tensors = "48a634ad-e948-5137-8d70-aa71f2a747f4"

[compat]
Tensors = "1.17.0"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
